#!/usr/bin/env python3
"""Quarantine mismatched optional PDFs into docs/<dir>/_suspects/.

We only move optional PDFs:
- 綠鞋悉行.pdf
- 穩價期終.pdf

Source of truth: reports/pdf_audit_mismatch.json generated by scripts/audit_pdfs.py

This script is intentionally conservative:
- Only moves files that still exist at the recorded path.
- Only moves the two optional filenames.

Usage:
  python3 scripts/audit_pdfs.py
  python3 scripts/quarantine_mismatched_optionals.py --apply

Note: _suspects/ is expected to be git-ignored/cleaned later as desired.
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


OPTIONAL = {"綠鞋悉行.pdf", "穩價期終.pdf"}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", type=Path, default=Path.cwd())
    ap.add_argument("--mismatch", type=Path, default=Path("reports/pdf_audit_mismatch.json"))
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()

    repo = args.repo.resolve()
    mismatch_path = repo / args.mismatch
    if not mismatch_path.exists():
        raise SystemExit(f"mismatch file not found: {mismatch_path}")

    j = json.loads(mismatch_path.read_text(encoding="utf-8"))
    mismatches = j.get("mismatches") or []

    moved = 0
    skipped = 0

    for m in mismatches:
        fn = m.get("file")
        rel = m.get("path")
        if fn not in OPTIONAL:
            skipped += 1
            continue
        if not rel:
            skipped += 1
            continue

        src = repo / rel
        if not src.exists():
            skipped += 1
            continue

        dst_dir = src.parent / "_suspects"
        dst_dir.mkdir(exist_ok=True)
        dst = dst_dir / src.name

        if args.apply:
            # overwrite if exists
            if dst.exists():
                dst.unlink()
            shutil.move(str(src), str(dst))
        moved += 1

    print(f"moved={moved} skipped={skipped} apply={args.apply}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
